### ISSUE TITLE
[rally-sdk] extensions can become unpaused after browser or extension restart

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally#102]
Steps to reproduce in the Facebook Pixel Hunt extension:

1. set `studyPaused` to `true`
2. Observe `Facebook Pixel Hunt data collection pause` in the console
3. Restart browser

Expected:

`Facebook Pixel Hunt data collection pause` is observed, and data collection stops

Actual:
`Facebook Pixel Hunt data collection pause` is observed, followed by `Facebook Pixel Hunt data collection start` and data collection is resumed.

**Comment by marniepw** [comment]
@rhelmer can you confirm this is still happening now that the FPH has been paused in production?

**Comment by rhelmer** [comment]
> @rhelmer can you confirm this is still happening now that the FPH has been paused in production? (I'm assuming you saw this on staging...)

I think it is, it's hard to verify though now that we've disabled enrollment :) I'll test it today.

Note that we're also working on blocking incoming pings on the server-side, which is probably a good idea to do in any case (just in case clients ignore our pause messages for reasons outside of our control)

**Comment by rhelmer** [comment]
> > @rhelmer can you confirm this is still happening now that the FPH has been paused in production? (I'm assuming you saw this on staging...)
> 
> I think it is, it's hard to verify though now that we've disabled enrollment :) I'll test it today.
> 
> Note that we're also working on blocking incoming pings on the server-side, which is probably a good idea to do in any case (just in case clients ignore our pause messages for reasons outside of our control)

https://bugzilla.mozilla.org/show_bug.cgi?id=1779801
