### ISSUE TITLE
Push updates to Attention Stream w/Stanford probes

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#162]
For our August release, we need to release updates to the Attention Stream extensions.

- [x] Firefox/AMO release, tracked: https://mozilla-hub.atlassian.net/browse/ADDONSOPS-191
- [x] Chrome Store release, dependent on: https://bugzilla.mozilla.org/show_bug.cgi?id=1783960

**Comment by marniepw** [comment]
Friday, August 12:

- Chrome extension is live
- Firefox extension has been uploaded for review (Glean bug fixed). Ticket is unassigned.

**Comment by aaga** [comment]
The AMO review for this update has hit a block. They are unable to reproduce an identical build. I believe this is because we removed our "shrinkwrap" from the monorepo. I will look into this further on Monday, but we may have to resubmit.

cc @jepstein @marniepw

**Comment by marniepw** [comment]
Rob will look into this when he returns.
