### ISSUE TITLE
Add Pixel Hunt measurements to Attention Stream

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#167]
Should we add FBPH measurements to the Attention Stream? ~~Cookie perms will change.~~

**Comment by aaga** [comment]
@marniepw Which cookie perms are you referring to here? I believe Rob and I determined that adding the Pixel tracker wouldn't require new extension permissions. Although I believe it will (legally) require new consent from the user.

**Comment by marniepw** [comment]
OK, good to know we have it covered. This ticket was a quick note I took during a meeting, so no doubt things have changed. I'll update the first comment.

**Comment by marniepw** [comment]
Estimate: few days of work.

Priority order: 
1. ad work, part 1
2. pixel hunt
3. ad work, part 2
