### ISSUE TITLE
Dynamically alter the appearance of the study card to reflect what a user has consented to (timebox at 2 days)

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#205]
Based on the boolean set in #203, can we dynamically alter the study card on the platform such that a user will see the data points that they have consented to.

**TIMEBOX DYNAMIC SOLUTION TO 2 DAYS**

If a dynamic solution cannot be completed in 2 days, then fallback is to address with this copy:

**_(THIS IS THE CORRECT, LEGALLY APPROVED TEXT)_**

**Key Data Collected**

- Visits to web page URLs
- Time spent on urls
- Time spent playing media on each webpage
- Your Rally demographics
- On certain news pages, the full text of the article and the ads on the article’s page
- On YouTube pages, data about the recommended ads a user sees*
- The data sent to Facebook and Google through their respective pixels*

*If you joined prior to 9/12/2021, these measurements are excluded

**Comment by marniepw** [comment]
Simple text change for the short-term, then look into dynamic updates next.

**Comment by jepstein** [comment]
Static text issues #240 #239
