### ISSUE TITLE
Firefox: After saving profile, browser doesn't scroll back up

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#226]
https://stage.rally-web.nonprod.dataops.mozgcp.net/

1. Either sign up for a new account or go to Manage Profile
2. Enter in values in the survey
3. Scroll to the bottom and hit save

https://user-images.githubusercontent.com/444356/189186155-206dde6b-fe20-43c0-af3c-00b74e712f5d.mov

Result: On Firefox, window is still scrolled down to that position, so when studies loads, it is at the bottom.

This occurs when editing the profile information for first time (when creating account) and for any subsequent time (manage profile on existing account).

It works as expected in Chrome

Expect: Window is scrolled back to the top when the studies page loads.

**Comment by Carla-Moz** [comment]
@jepstein, I can't reproduce on Firefox. Could you please take a snapshot of the whole window so I can see if the scrollbar appears or not?
