### ISSUE TITLE
Dynamically read (and store?) UTMs on the RWP and pass that along to the extension stores; and vice versa

### ISSUE THREAD

**Issue by aaga** [mozilla-rally/rally#233]
1) When someone comes to the RWP via a UTM link (e.g. http://members.rally.mozilla.org/?utm_campaign=test), we should pass that along to the store when the user eventually clicks "Add Study Extension". (i.e. they should end up at https://addons.mozilla.org/en-US/firefox/addon/rally-attention-stream?utm_campaign=test)

2) Similarly, if we send someone directly to the store via a UTM link (e.g. https://addons.mozilla.org/en-US/firefox/addon/rally-attention-stream?utm_campaign=test), that code should get passed to the RWP so that it shows up in Google Analytics (i.e. they should land on http://members.rally.mozilla.org/?utm_campaign=test after they install the extension).

@rhelmer please check my understanding here. I think we definitely don't have the capability for (1), I know that store UTM codes get sent to Glean but I'm not sure if it will show up in Google Analytics for the site.

**Comment by rhelmer** [comment]
> 1. When someone comes to the RWP via a UTM link (e.g. http://members.rally.mozilla.org/?utm_campaign=test), we should pass that along to the store when the user eventually clicks "Add Study Extension". (i.e. they should end up at https://addons.mozilla.org/en-US/firefox/addon/rally-attention-stream?utm_campaign=test)

This is covered by https://github.com/mozilla-rally/rally/pull/293

> 
>     2. Similarly, if we send someone directly to the store via a UTM link (e.g. https://addons.mozilla.org/en-US/firefox/addon/rally-attention-stream?utm_campaign=test), that code should get passed to the RWP so that it shows up in Google Analytics (i.e. they should land on http://members.rally.mozilla.org/?utm_campaign=test after they install the extension).
> 
> 
> @rhelmer please check my understanding here. I think we definitely don't have the capability for (1), I know that store UTM codes get sent to Glean but I'm not sure if it will show up in Google Analytics for the site.

This bit was fixed in https://github.com/mozilla-rally/rally/pull/255
