### ISSUE TITLE
Entering incorrect password on email login doesn't show error text

### ISSUE THREAD

**Issue by aaga** [mozilla-rally/rally#242]
There should be a text prompt in addition to the red exclamation icon.

<img width="390" alt="Screen Shot 2022-09-14 at 7 33 55 PM" src="https://user-images.githubusercontent.com/7362472/190280814-b29b3298-2984-4231-aba7-c1482dfc6d9b.png">

**Comment by Carla-Moz** [comment]
@thomik-corp , if you're working on this, let me know and un-assign me, otherwise I'll start work on it.
