### ISSUE TITLE
Studies page copy is incorrect for Firefox 

### ISSUE THREAD

**Issue by aaga** [mozilla-rally/rally#243]
The copy on the main studies page should change dynamically depending on the user's browser. These are the pieces of text that should change (currently in Firefox they all still say Chrome):

<img width="723" alt="Screen Shot 2022-09-14 at 7 38 00 PM" src="https://user-images.githubusercontent.com/7362472/190281248-0cbf460c-d4e9-4a3e-bb42-f43160c70333.png">

**Comment by Carla-Moz** [comment]
@thomik-corp  , if you're working on this, let me know and un-assign me, otherwise I'll start work on it.
