### ISSUE TITLE
set attribution (UTM) codes on links to browser extensions stores

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally#268]
To track attribution, we need to be able to attribution (UTM) codes on incoming links, and to set those in outbound links to the Chrome and Firefox store:

![image](https://user-images.githubusercontent.com/61412/191555373-835ba631-354c-4762-882c-377250dce776.png)

For example, if a user were to follow a link to:
https://members.rally.mozilla.org/?utm_source=test-source-1&utm_medium=test-medium-1&utm_campaign=test-campaign-1&utm_term=test-term-1&utm_content=test-content-1

Then we want that query string to be preserved in outbound links to AMO and CWS:

https://addons.mozilla.org/en-US/firefox/addon/rally-attention-stream/?utm_source=test-source-1&utm_medium=test-medium-1&utm_campaign=test-campaign-1&utm_term=test-term-1&utm_content=test-content-1
https://chrome.google.com/webstore/detail/rally-attention-stream/bahhehaddofgkccippmjcecepdakppme?utm_source=test-source-1&utm_medium=test-medium-1&utm_campaign=test-campaign-1&utm_term=test-term-1&utm_content=test-content-1

If the user installs the extension first, then the extension is responsible for sending attribution codes to the members.rally.mozilla.org signup page (as part of onboarding the user, getting them to log in to the site etc) so I don't think there's anything special we need to do there.

**Comment by compzilla** [comment]
I canceled the 3SPot ticket for this.

**Comment by rhelmer** [comment]
I think we can do something similar here that we did for the marketing site (React might make it a little easier vs. the vanilla JS): https://github.com/mozilla-rally/site/pull/717

1. parse and store any inbound UTM codes in localStorage (overriding any previously stored aka "last-touch")
2. add UTM codes to outbound links, using `click` event handler

I've been reading about and looking at how GA/GTM works, it takes a very similar approach. Preserving UTM codes on inbound links is strongly discouraged, so it's only set for outbound links.
