### ISSUE TITLE
Losing UTM codes on redirect to login page

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#305]
1. Log out of members site.
2. go to https://rally.mozilla.org/support-local-news/?utm_medium=cpc&utm_source=pocket&utm_campaign=pocket20220812&utm_content=local-news
3. Hit Install Rally for Chrome/Firefox button

result:
Opens members signup page without utm codes

https://user-images.githubusercontent.com/444356/193342618-7a593b6f-7228-40cc-8e12-3912063e2034.mov

expect: 
utm codes are preserved.

I suspect this is due to the redirect that is happening for unauthenticated users. It is working as expected if the user is signed in.

**Comment by rhelmer** [comment]
@jepstein UTM codes are stored in local storage and applied to outbound links, using UTM codes for inbound links is discouraged (I can find a more authoritative source but https://www.searchseven.co.uk/blog/why-using-utm-parameters-on-internal-links-is-a-very-bad-idea/ is a quick one I found on Google)
