### ISSUE TITLE
Copy / Privacy cancel: on hold

### ISSUE THREAD

**Issue by tangcasey** [mozilla-rally/rally#329]
Need copy for friction page after a user hits cancel on the privacy page

<img width="1341" alt="Screen Shot 2022-10-04 at 11 05 05 AM" src="https://user-images.githubusercontent.com/59886626/193855529-19015b51-65cf-44ba-9872-d68e9732acf6.png">

**Comment by KennedyM-zillian** [comment]
@knowtheory is this issue closed?
