### ISSUE TITLE
Spreadsheet for Paid Media Ad Creatives and Copy Specs

### ISSUE THREAD

**Issue by compzilla** [mozilla-rally/rally#343]
These have mostly been in my head, but will get them all in one place, so I can get help with some of it :) 

- [x] Pinterest Creative
- [x] Pinterest Copy
- [x] Twitter Creative
- [x] Twitter Copy
- [x] Facebook Creative
- [x] Facebook Copy
- [x] GDN Creative
- [x] GDN Copy
- [x] Gannett Creative
- [x] Gannet Copy
- [x] Pocket Creative
- [x] Pocket Copy
- [x] Reddit Creative
- [x] Reddit Copy

**Comment by compzilla** [comment]
@marniepw - every time I add issues to Kanban Project - it adds it to "Backlog" - is that where all issues should begin? Is that where issues are assigned to ppl? Or should I change that to "in progress" or what?

**Comment by marniepw** [comment]
@compzilla yep, think of the backlog category as work "to do." If you're actively working on it, then "in progress" would be the correct categorization.

**Comment by compzilla** [comment]
Here is the document I'm working on: https://docs.google.com/spreadsheets/d/137z5eSdpD-nwQHgpcBPdU1Y-zVFSF-0dl7R_C1X_gbI/edit#gid=0

**Comment by compzilla** [comment]
The document is complete.
