### ISSUE TITLE
Account creation - is it possible to have a toast validation instead of the current validation page?

### ISSUE THREAD

**Issue by tangcasey** [mozilla-rally/rally#354]
## Current experience 
In the user inbox, once the user clicks on the Rally verification link, the user is brought to a page confirming the success of their email verification and that they can return to the sign-in page. 

<img width="479" alt="Screen Shot 2022-06-03 at 12 34 17 PM" src="https://user-images.githubusercontent.com/59886626/171907645-fd475a2c-8d72-45c6-b24f-71e885f827a7.png">

## Design
Once the email account is verified - is it possible to bring the user to the sign-in screen with a toast confirmation? This was in the Figma design so I'm wondering if this is even possible at all.

[Figma reference](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2147%3A24109)

![Screen Shot 2022-06-03 at 5 52 55 PM](https://user-images.githubusercontent.com/59886626/171959019-891ab696-816d-4e7c-b0d1-7b17c61bf1a8.png)

## Solution B?
If we can't use toast and have to use a page - please let me know. The page needs to follow the other card confirmation styles.

**Comment by marniepw** [comment]
Closing as part of the Rally wind down.
