### ISSUE TITLE
Show error messages to the user if failures in backend services are encountered

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally#361]
## Story

As a Rally user, I want to be informed about site errors so that I can resolve the situation and continue using the site.

## Definition of Done (optional)

Any GCP services being down or unreachable (Cloud Firestore, etc) should cause the website to display an error, and (depending on context) take additional action such as logging the user out and forcing them to re-authenticate.

**Comment by marniepw** [comment]
Closing as part of Rally wind down.
