### ISSUE TITLE
Copy editing for Princeton

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#367]
Review copy doc: https://docs.google.com/spreadsheets/d/1GODt2j4jJAT_rEQNNMUgBhVbXwwbr9lCNNTncliN-P8/edit?usp=sharing

**Comment by than-mozilla** [comment]
@rhelmer & @jepstein I can't find the branch that was used to generate https://zippy-marigold-2ac4dd.netlify.app/get-paid-for-your-data/ so i was unable to make these changes to a branch.

**Comment by jepstein** [comment]
@rhelmer - were you working on a fork? can you bring those over?

**Comment by than-mozilla** [comment]
Ben Kaiser's suggestion

# Get paid $10 to help Princeton Researchers study online media during the 2022 Midterm Elections.

Contribute your data (and get paid for it) in four easy steps:

1. Consent to the research and answer a short survey
2. Create an account to Join Rally
3. Download the Rally Extension and get paid $5
4. Contribute data for 60 days and get paid another $5

**Comment by jepstein** [comment]
I've copied over Rob's fork and pushed these live.

https://rally.mozilla.org/get-paid-for-your-data/
https://rally.mozilla.org/donate-your-data/

closing this ticket - related work tracked in https://github.com/mozilla-rally/site/issues/738
