### ISSUE TITLE
Existing, already consented user hitting privacy policy and add extension screen

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#389]
Testing on stage - https://members.rally.allizom.org/ or https://stage.rally-web.nonprod.dataops.mozgcp.net/
(cannot reproduce locally)

1. Sign in with an existing user who has already consented (either email or google)

result:
after signing in, user gets the privacy policy modal again. And is still asked to add the extension.

expect:
that an existing user who has already consented ends up on the product discovery page ("studies")

**Comment by jepstein** [comment]
https://user-images.githubusercontent.com/444356/195100707-64667ba8-cab1-43e1-b49b-5da1133b1a24.mov

**Comment by aaga** [comment]
@jepstein can we close this issue?

**Comment by Carla-Moz** [comment]
@jepstein I'm just now seeing this ticket. Let me investigate before closing.

**Comment by jepstein** [comment]
I am no longer repro'ing on live. This was from before Ashwin refactored.

**Comment by Carla-Moz** [comment]
Gotcha! Then please feel free to close.
