### ISSUE TITLE
"Reactivate" button shows when it's not supposed to

### ISSUE THREAD

**Issue by aaga** [mozilla-rally/rally#405]
Steps:
1. Create a new account
2. Agree to the privacy policy
3. The first time you land on Home Page after accepting privacy policy, the "Reactivate" button is visible, but it shouldn't be. Upon refresh the button disappears

**Comment by rhelmer** [comment]
I just ran into this too, I can reproduce it reliably by installing the extension first, then visiting the site and creating an account.
