### ISSUE TITLE
Pixel Pervasiveness

### ISSUE THREAD

**Issue by than-mozilla** [mozilla-rally/rally#414]
## As a Rally user...
I want to see pixels tracking me (make the invisible visible) so that I can understand how tracking pixels operate, who the worst offenders are, and ultimately what I can do about it.

## Hypothesis
users want to understand how they are tracked on the web

## Measures

how will you know your hypothesis is correct?

* 50% don’t immediately close tab (under 1 second?) (time on page measured with google analytics) 
* 25% click the CTA link (also Google Analytics)
Future: how many share infographic on social media

## Helpful Sources

[Ashwin's now v. later proposal](https://docs.google.com/presentation/d/1KaDegdpEKbt1tIBbjZqbq0LDlkFiS2eCAvpiTRmitPg/edit#slide=id.g10015baea0b_0_13)
[Sydette's doc](https://docs.google.com/document/d/1-tDwkvFMa7j-tQh0228Zt6JbwoHw-6hPUIMPV7fkMc4/edit)
[Pixel Story Telling](https://docs.google.com/document/d/1e_Ln8Vq5Ob1QA7CWWXqzwOBfgxOKW2h52ax2DM4kOls/edit#)

## Potential tickets
- [x] #418
- [x] #419
- [x] #420
- [x] #421
- [x] #422
- [x] #423
- [x] #424
- [x] #425
- [x] #426

**Comment by marniepw** [comment]
Potential tickets
[Slide deck](https://docs.google.com/presentation/d/1KaDegdpEKbt1tIBbjZqbq0LDlkFiS2eCAvpiTRmitPg/edit#slide=id.g10015baea0b_0_13)
[Ashwin's now v. later proposal](https://docs.google.com/presentation/d/1KaDegdpEKbt1tIBbjZqbq0LDlkFiS2eCAvpiTRmitPg/edit#slide=id.g10015baea0b_0_13)
- [ ] Host new tab page
- [ ] Design of new tab page
- [ ] Graphic for new tab page: what domains are we displaying? Is this interactive? What message are we trying to send w/the graphic?
- [ ] Instrument (w/GA) new tab page
- [ ] 
- [ ] Extension update: opening a new tab when update gets installed
- [ ] Do we have an explainer on how the pixel works? Where can we point users? Blog post? Markup explainer on the pixel. Sharable infographic?
- [ ] Where does CTA land the user?
- [ ] [Sydette's doc](https://docs.google.com/document/d/1-tDwkvFMa7j-tQh0228Zt6JbwoHw-6hPUIMPV7fkMc4/edit)
