### ISSUE TITLE
What can Rally do for you?

### ISSUE THREAD

**Issue by than-mozilla** [mozilla-rally/rally#416]
## As a Rally user…
I want to be able to pick new ideas or contribute my ideas for what I’d like Rally to do for me or my community, so I can feel a part of building it.

## Hypothesis
Users want to help build Rally's future by picking new product features or offering suggestions for how Rally could work for them. By gauging what users need, Rally will move in the direction of delivering features of high value to users. 

Alternative: Users will join Rally and contribute their feedback/ideas if Rally [responds? Provides a path to impact on community ideas?]

## Measures
* Measuring number of completed surveys

**Comment by marniepw** [comment]
Closing as part of Rally wind down.
