### ISSUE TITLE
Design/layout of marketing site new tab page

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#420]
_**As a Rally user/person interested in Rally, I want to see a page on the marketing site that contains #423, so that I can understand what's being collected on me.**_

We have templates from Threespot; @KennedyM-zillian to find those.
Do we have existing components we can use? @Carla-Moz says no. Would need to create a new page.

**Comment by aaga** [comment]
![image](https://user-images.githubusercontent.com/7362472/198084256-4a291f86-3c60-42d4-a7d4-97b8a0de67e4.png)

first pass

**Comment by marniepw** [comment]
Template proposal: https://rally.mozilla.org/how-rally-works/data-and-privacy/index.html
