### ISSUE TITLE
Copy for new tab page

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#421]
https://docs.google.com/document/d/1e_Ln8Vq5Ob1QA7CWWXqzwOBfgxOKW2h52ax2DM4kOls/edit#

https://docs.google.com/document/d/1-tDwkvFMa7j-tQh0228Zt6JbwoHw-6hPUIMPV7fkMc4/edit

**Comment by KennedyM-zillian** [comment]
Copy is in Final edits with @KimBMozilla

**Comment by KimBMozilla** [comment]
I copyedited Draft 3 -- ready for last corrections (mostly missing links). @KennedyM-zillian
