### ISSUE TITLE
Extension updates: opening a new tab when update gets installed

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#425]
For extension (Chrome and Firefox) updates only
Timer for when the user is idle
Take focus to the new page; decision needed on URL and whether UTM code is needed

**Comment by marniepw** [comment]
Thursday: nearly ready to push out for review. Push into hidden state.

**Comment by aaga** [comment]
Im proposing we send users to rally.mozilla.org/pixel-psa

This is where the infographic will live, and once we submit extension for review this can't be changed.

@compzilla please advise what the UTM codes should be

**Comment by jepstein** [comment]
What are we trying to test and how might we measure it?

I think we're testing the behavior of someone who receives the new tab, so in that way, I think of this like its own campaign. Which leads me to think we want a new set of UTM codes in this case.
If others agree, let's use the [UTM generator](https://docs.google.com/spreadsheets/d/1cJLbMZy86pgZEjiq-SMxnknzxm_Yw-RlIIg_3OuaJrU/edit?usp=sharing) to create.

**Comment by aaga** [comment]
@jepstein that's what I was thinking as well

**Comment by compzilla** [comment]
[rally.mozilla.org/pixel-psa/?utm_medium=blog&utm_source=traffic&utm_campaign=pixel-psa](http://rally.mozilla.org/pixel-psa/?utm_medium=blog&utm_source=traffic&utm_campaign=pixel-psa)

**Comment by compzilla** [comment]
Do we want a different UTM for each Mozilla and Chrome?

**Comment by marniepw** [comment]
Decision ^ was no. From @rhelmer "Yeah GA has the browser and OS/platform info already, there probably isn't a need to differentiate that w/ our own utm codes too"

**Comment by marniepw** [comment]
Chrome has been approved, but is in hidden state. Still waiting on AMO.

**Comment by aaga** [comment]
Chrome is live
