### ISSUE TITLE
Prototype interactive graphic for Pixel Pervasiveness

### ISSUE THREAD

**Issue by than-mozilla** [mozilla-rally/rally#431]
Tools like datawrapper or flourish would make it possible to create interactive layers to explore for the graphic on the Pixel Pervasiveness page, if we can export data with the correct structure

**Comment by betling** [comment]
--adjust hover action so that tooltip box comes up, but nodes of different color don't disappear
--clarify language about colors and what data represents (pixel vs. no pixel vs meta pixel) and data behind labels is accurate (perhaps regenerate map since it's been a couple weeks.)

**Comment by betling** [comment]
gonna call this done for now but we can still iterate as we get closer to launch.  it's currently not possible to prevent nodes of different colors from disappearing but other changes made.  https://datawrapper.dwcdn.net/cznEU/4/
code for embedding the image is on that datawrapper site.
