### ISSUE TITLE
Spot Video

### ISSUE THREAD

**Issue by KennedyM-zillian** [mozilla-rally/rally#435]
[Scope](https://docs.google.com/document/d/1ap6hVY65rK-SPajUorGwfcQYbI1qc7BFFANZtnsNFcI/edit?usp=sharing)
[Project Charter Doc ](https://docs.google.com/document/d/1ZnVx9y9rs3Ki3CVt2OEd9vETJ3FJfqGyoShTVVvaugU/edit?usp=sharing&resourcekey=0-BaoSvFhEt0FfUUiEINpDlg)

**Comment by KennedyM-zillian** [comment]
Project Sketch in Review with @knowtheory @KimBMozilla

**Comment by marniepw** [comment]
Closing as part of the Rally wind down.
