### ISSUE TITLE
Push attention-stream 0.4.3 release to Firefox store (AMO)

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally#44]

**Comment by rhelmer** [comment]
Attempted to upload on 06/19/22 using version number `0.4.1` [to match Chrome version](https://github.com/mozilla-rally/rally/issues/43#issuecomment-1159792106), but AMO is not accepting it:

> Add-ons using an ID ending with this suffix need to be signed with privileged certificate before being submitted

I've tried with both `@rally.mozilla.org` and `@mozilla.org` suffixes, which we use for other privileged add-ons, so the expectations of the AMO team must have changed here.

I'll get in contact with them.

**Comment by rhelmer** [comment]
> Attempted to upload on 06/19/22 using version number `0.4.1` [to match Chrome version](https://github.com/mozilla-rally/rally/issues/43#issuecomment-1159792106), but AMO is not accepting it:
> 
> > Add-ons using an ID ending with this suffix need to be signed with privileged certificate before being submitted
> 
> I've tried with both `@rally.mozilla.org` and `@mozilla.org` suffixes, which we use for other un-privileged add-ons, so the expectations of the AMO team must have changed here.
> 
> I'll get in contact with them.

This will be fixed on AMO, discussion in https://matrix.to/#/!NOYruJxlGuAToxNIat:mozilla.org/$bX1O7oKEYGaQbB7rnLAUuLUuVu6BAi3yysvbtZWmj_g?via=mozilla.org&via=matrix.org&via=ajay.app

**Comment by marniepw** [comment]
[Bug fixed](https://github.com/mozilla/addons-server/issues/19478), removing the "bug" label and "needs Mozilla" label.
