### ISSUE TITLE
Product Page Explorations

### ISSUE THREAD

**Issue by Carla-Moz** [mozilla-rally/rally#453]
[Figma link](https://www.figma.com/file/OVlnSF6b56ZDeHvhkkLWP4/Discovery-Page-Sketches----Fall-2022?node-id=0%3A1)

related to #442 

- Helping design with figma explorations  
- Helping the comms teams with the impact section of product page

**Comment by Carla-Moz** [comment]
@aaga Why did you close this?

**Comment by aaga** [comment]
Sorry I should have closed with comment!
Since the Product Page is being tracked in this [META ticket](https://github.com/mozilla-rally/rally/issues/442) which has the Figma link in it, I figured we didn't need this one.

Feel free to re-open though

**Comment by aaga** [comment]
If you re-open, just make sure to link it in that meta ticket
