### ISSUE TITLE
Copy for landing page @KennedyM-zillian

### ISSUE THREAD

**Issue by compzilla** [mozilla-rally/rally#461]
https://docs.google.com/document/d/1tMR-GlBn6atCyewATtIJKXbWpwV9_lWt8ahdXYY5Q-4/edit#

**Comment by KennedyM-zillian** [comment]
What is this landing page?

**Comment by compzilla** [comment]
We are going to test an editorial type ad on Pocket that will have it's own landing page. We are re-publishing the Hey Jane article, and we will need language before/after the article encouraging people to join Rally.

**Comment by marniepw** [comment]
Copy doc: https://docs.google.com/document/d/1tMR-GlBn6atCyewATtIJKXbWpwV9_lWt8ahdXYY5Q-4/edit#

**Comment by marniepw** [comment]
Closing, duplicate of #553  (I think)
