### ISSUE TITLE
Needed Links

### ISSUE THREAD

**Issue by KennedyM-zillian** [mozilla-rally/rally#483]
@rhelmer Is there a link to a sign-up for communications that you know about?
<img width="735" alt="Screen Shot 2022-11-08 at 1 55 44 PM" src="https://user-images.githubusercontent.com/110490470/200684170-d5839c47-f229-421e-8238-74cb4b52ec9f.png">

@rhelmer Need a link for [this](https://mc.sendgrid.com/dynamic-templates/d-28c4b68bfef54320b0cefa6e973cab9a/version/72435731-6999-4595-9794-387522e51fcd/editor/modules?moduleId=258c46af-41aa-4429-8cd6-1f05647a89a3) button as well. 
<img width="708" alt="Screen Shot 2022-11-14 at 1 35 15 PM" src="https://user-images.githubusercontent.com/110490470/201770613-4e0e32f6-2011-4e4d-900d-9fb4d6e8a65d.png">

**Comment by rhelmer** [comment]
> @rhelmer Is there a link to a sign-up for communications that you know about? 

I'm not sure about this one, finding out now.

> 
> @rhelmer Need a link for [this](https://mc.sendgrid.com/dynamic-templates/d-28c4b68bfef54320b0cefa6e973cab9a/version/72435731-6999-4595-9794-387522e51fcd/editor/modules?moduleId=258c46af-41aa-4429-8cd6-1f05647a89a3) button as well. <img alt="Screen Shot 2022-11-14 at 1 35 15 PM" width="708" src="https://user-images.githubusercontent.com/110490470/201770613-4e0e32f6-2011-4e4d-900d-9fb4d6e8a65d.png">

https://members.rally.mozilla.org should do the right thing here, once users have logged in the site should auto-detect what steps are still needed for their account.

**Comment by rhelmer** [comment]
> > @rhelmer Is there a link to a sign-up for communications that you know about?

I think the right one for this is: https://rally.mozilla.org/newsletter/index.html

That signs up for the newsletter, the only way to opt-in to marketing-related email right now is when you sign up for a Rally account on the members site.

**Comment by KennedyM-zillian** [comment]
Thanks!
