### ISSUE TITLE
Waitlist Email Approval 

### ISSUE THREAD

**Issue by KennedyM-zillian** [mozilla-rally/rally#484]
@KimBMozilla
Waitlist email in [SendGrid](https://mc.sendgrid.com/dynamic-templates/d-23ea4ad37b614d3fba3ce60fb30153f8/version/e694070c-f939-4356-8cfd-9799d4fb2da8/editor)

Please leave final edits and approval comments in this thread. 

@compzilla for visibility

**Comment by KimBMozilla** [comment]
feedback on forwarding/mobile layout:

**Comment by KimBMozilla** [comment]
feedback on email content:

**Comment by KimBMozilla** [comment]
@compzilla @KennedyM-zillian @marniepw 
100% done with final edits -- have at it, and my apologies for the delay!
