### ISSUE TITLE
Pixel Pervasiveness section

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#502]
[Figma](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4708%3A90197&t=7s73CUqF4v2G1Qki-0)
- [x] Create Pixel Pervasiveness component @aaga 
- [x] Place [Pixel graphic on right](https://github.com/mozilla-rally/rally/issues/514) @betling 
- [x] [Content](https://github.com/mozilla-rally/rally/issues/520) on left @KennedyM-zillian #520

**Comment by compzilla** [comment]
2nd draft of content in this document: ([https://docs.google.com/document/d/1-HAozb3TOhcg6pZpE6orEsp1CLScXlWrmvAwVb4BkPA/edit#](https://docs.google.com/document/d/1-HAozb3TOhcg6pZpE6orEsp1CLScXlWrmvAwVb4BkPA/edit#))

A tracking pixel is a tiny bit of code in the background of a website that allows both the installer, e.g. a shoe company website, and the social media platform that owns the pixel, e.g. Facebook, to gather information about visitors to that site. There are different types of tracking pixels – not all are created equal. Some trackers collect browsing data, including which websites you visit and what ads you click. Others, however, capture much more personal and sensitive information. We’ve identified the top 1000 sites visited by the Rally community, and through data contributions like yours, can show which sites are tracking more than just those bunny slippers that you’ve had in your cart for the last month.
