### ISSUE TITLE
Rally "Impact" content

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally#508]
[Figma link](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4708%3A90197&t=MpspU8s9bchHB3BV-0)
The following content will live in the component being built in #507
- [x] Left section will house an image and [copy](https://docs.google.com/document/d/1-HAozb3TOhcg6pZpE6orEsp1CLScXlWrmvAwVb4BkPA/edit#) @KennedyM-zillian 
- [x] Right section will house a several pieces of [content](https://docs.google.com/document/d/1-HAozb3TOhcg6pZpE6orEsp1CLScXlWrmvAwVb4BkPA/edit#) that link out to news stories @Sydettemozilla 
- [x] Final copy edits: @KimBMozilla #517

**Comment by compzilla** [comment]
Third draft:

Title:
Data Health = Medical Health

Copy:
Medical records have always been one of the most sacred categories of data. As part of our work with the [Pixel Hunt](https://rally.mozilla.org/past-studies/facebook-pixel-hunt/) study, the collective data from the Rally community showed many breaches of healthcare privacy in hospital systems across the U.S. This resulted in several news stories, six class action lawsuits, and the attention of legislators who are considering how to vote on [H.R. 8152 - American Data Privacy and Protection Act (ADPPA)](https://www.congress.gov/bill/117th-congress/house-bill/8152/text#toc-H4B489C75371741CBAA5F38622BF082DE). 

With the overturn of Roe v. Wade and anti-trans legislation on the rise, the ability to keep healthcare data private is more critical than ever. The American Medical Association released a [study](https://www.ama-assn.org/press-center/press-releases/patient-survey-shows-unresolved-tension-over-health-data-privacy) this year showing that more than 92% of patients “believe privacy is a right” and “their health data should not be available for purchase.” However, confidence in the security of healthcare data has been eroding, and the results of the Pixel Hunt study offer quantitative evidence that supports this sentiment.

Check back here for updates about the continued impact of the Pixel Hunt, which has far-reaching implications not just for medical health, but for data health as well.

**Comment by compzilla** [comment]
Right side of impact section (Links with slugs)

Second draft:

#1
Paper - Date:
The Markup - June 16, 2022
Title:
[Facebook Is Receiving Sensitive Medical Information from Hospital Websites](https://themarkup.org/pixel-hunt/2022/06/16/facebook-is-receiving-sensitive-medical-information-from-hospital-websites)
Slug:
The Markup uses Rally’s crowdsourced data to find that 33 of Newsweek’s top 100 hospitals in the U.S. sent sensitive data to Meta via the Facebook tracking pixel. Experts say some hospitals’ use of Meta’s ad tracking tool may violate HIPAA laws protecting health information. 


#2
Paper - Date: 
Bloomberg - June 17, 2022
Title: [Meta Sued Over Claims Patient Data Secretly Sent to Facebook](https://www.bloomberg.com/news/articles/2022-06-17/meta-sued-over-claims-patient-data-secretly-sent-to-facebook?leadSource=uverify%20wall)
Slug:
Meta is being sued over claims that private medical data was being shared secretly with Facebook when patients accessed healthcare portals. Rally’s collective data reveals that Facebook’s tracking pixel redirected patient communications and other supposedly “secure” information without consent from patients and in violation of federal and state laws, according to a class action lawsuit on behalf of millions of patients.

#3
Paper - Date:
The Markup - July 1, 2022
Title:
[Online Abortion Pill Provider Hey Jane Used Tracking Tools That Sent Visitor Data to Meta, Google, and Others](https://themarkup.org/pixel-hunt/2022/07/01/online-abortion-pill-provider-hey-jane-used-tracking-tools-that-sent-visitor-data-to-meta-google-and-others)
Slug: Once the data contributions from Rally highlight the privacy issues, and The Markup makes Hey Jane aware that it was unknowingly sending sensitive data to Meta, the online women’s healthcare provider removes the Facebook tracking pixel from their website. 

#4
Paper - Date:
Stat News - Sept. 19, 2022
Title:
[Meta faces mounting questions from Congress on health data privacy as hospitals remove Facebook tracker](https://www.statnews.com/2022/09/19/facebook-meta-pixel-congress-health-data/)
Slug:
Senators press Facebook/Meta about its access to sensitive medical data once finding out from The Markup and Mozilla Rally’s data that the company’s pixel tracking tool collects details about patients’ doctor’s appointments, prescriptions, and health conditions on hospital websites.

#5
Paper - Date:
Health IT Security - October 21, 2022
Title:
[VA Senator Expresses Health Data Privacy Concerns in Letter to Meta](https://healthitsecurity.com/news/va-senator-expresses-health-data-privacy-concerns-in-letter-to-meta)
Slug:
After The Markup’s investigation using Rally’s community data, Virginia Senator Mark R. Warner pens a letter to Meta CEO Mark Zuckerberg to address health data privacy concerns surrounding the Facebook tracking pixel.

**Comment by marniepw** [comment]
Final edits made today, 11/28.
