### ISSUE TITLE
In-Product Page Final Edits 

### ISSUE THREAD

**Issue by KennedyM-zillian** [mozilla-rally/rally#517]
@KimBMozilla 
Content Edits: Very detailed and focused on typos, punctuation, and any newly-introduced grammar/style edits.
Due: 11/21 @ noon EST. 
[This](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4708%3A90197&t=TRMe2ME2axsgp7Vs-0) is the FIGMA file 
[This](https://docs.google.com/document/d/1-HAozb3TOhcg6pZpE6orEsp1CLScXlWrmvAwVb4BkPA/edit#) is the link for the Copy.
You would be editing under Draft 3. Please let me know if you need me to walk through/discuss the document with you.
<img width="476" alt="Screen Shot 2022-11-18 at 11 55 26 AM" src="https://user-images.githubusercontent.com/110490470/202791098-747d0887-88ad-4270-ad87-3d689ee42583.png">

@marniepw

**Comment by KennedyM-zillian** [comment]
Content Edits are complete

**Comment by KennedyM-zillian** [comment]
Moving into final edits:
@KimBMozilla 
Final Edits: Very detailed and focused on typos, punctuation, and any newly-introduced grammar/style edits.
Due: 11/23 @ noon EST. 
[This](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=4708%3A90197&t=TRMe2ME2axsgp7Vs-0) is the FIGMA file 
[This](https://docs.google.com/document/d/1-HAozb3TOhcg6pZpE6orEsp1CLScXlWrmvAwVb4BkPA/edit#) is the link for the Copy.
You would be editing under Draft 3. Please let me know if you need me to walk through/discuss the document with you.
<img width="476" alt="Screen Shot 2022-11-18 at 11 55 26 AM" src="https://user-images.githubusercontent.com/110490470/202791098-747d0887-88ad-4270-ad87-3d689ee42583.png">

@marniepw

**Comment by marniepw** [comment]
<img width="327" alt="Screen Shot 2022-11-28 at 10 44 03 AM" src="https://user-images.githubusercontent.com/33703387/204355831-cdedd933-12e9-45da-9863-9b7541eaf61d.png">
