### ISSUE TITLE
Launch ads @compzilla

### ISSUE THREAD

**Issue by compzilla** [mozilla-rally/rally#559]

**Comment by marniepw** [comment]
FB ads launched Wed/Thu Dec 14/15, midnight.
Pinterest ads launched Thursday Dec 15.
@compzilla tweaked spending based on prelim results of FB ads:
<img width="1122" alt="screen_shot_2022-12-15_at_6 04 17_pm" src="https://user-images.githubusercontent.com/33703387/208203155-f98ab25e-784e-4599-a0e1-0ec6659569e6.png">
