### ISSUE TITLE
Set up analysis environment for Attention Stream

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#60]
Submit bugzilla ticket to set up analysis environment

This is blocked by #61 and #62 

Content of Bugzilla ticket is [here](https://docs.google.com/document/d/1yldZ-GDEk7zknpcDu-lVHRGcJj7PZqGIkTWUU0MZ2nk/edit) and can be copied into a new bugzilla ticket

Here is a previous example (FPH) -- https://bugzilla.mozilla.org/show_bug.cgi?id=1744603

**Comment by jepstein** [comment]
All the content needed to file the bugzilla ticket can be found in this doc https://docs.google.com/document/d/1yldZ-GDEk7zknpcDu-lVHRGcJj7PZqGIkTWUU0MZ2nk/edit

The only thing left is adding the data review bugzilla ticket once data review is complete

**Comment by betling** [comment]
bug filed to set up environment is here:  https://bugzilla.mozilla.org/show_bug.cgi?id=1778196.

still need to add data review link once that's submitted.

**Comment by betling** [comment]
this is done for the main rally environment and I've gotten into it so closing.
