### ISSUE TITLE
Data Review of Attention Stream

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally#62]
- [x] Create doc
- [x] Doc reviewed internally
- [x] File [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1778367) ticket

**Comment by jepstein** [comment]
Document started at https://docs.google.com/document/d/19Of_9rY79WqMKb7aNZamBnCNIYjJRqzwahomVTmsmN0/edit#

A few areas need more detail

**Comment by marniepw** [comment]
Data review bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1778367

r+ by mmccorquodale 7/6/22.
